name: Doxygen

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  doxygen:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/configure-pages@v5
      - run: |
          sudo apt update
          sudo apt install cmake doxygen
          cmake -B build
          cmake --build build --target docs
      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./build/html
      - id: deployment
        uses: actions/deploy-pages@v4
